### PR TITLE
Include tests in sdist

### PR DESCRIPTION
**Pull request by mgorny**
Include the test suite in sdist archives, in order to make it possible for distribution packagers to use them rather than generated GitHub archives.

### CODE REVIEW

**Comment by cunla** [comment]
Why do you want the tests included?

**Comment by cunla** [comment]
> > Can you provide some context on it?
> 
> I don't understand what you're asking for. Gentoo Linux provides packages for various Python, well, packages. As part of package building process, users can opt in to run test suites against their system and Python versions. This way they can reduce the risk of hitting breakage at runtime, particularly if they're running a less common setup.

Have you tried running the tests for this package? Can you provide me how to run tests in gentoo for this?
The tests here run commands against `FakeRedis` (ie, the package) and real redis and compare the results. How does gentoo runs redis server before running the tests?

**Comment by mgorny** [comment]
Yes, we are running tests for quite a while. I admit there are a few known failures but most of them pass. We are starting a local redis server for the duration of the test suite. The code is here:

https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/fakeredis/fakeredis-2.10.2.ebuild#n66

To run ebuild with tests enabled, normally you run:

    FEATURES=test emerge -1v dev-python/fakeredis

However, this will also enable tests on all dependencies which can be time consuming. You can enable it per package by defining e.g. `/etc/portage/env/run-tests`:

    FEATURES="${FEATURES} test"

and then using in `/etc/portage/package.env`:

    dev-python/fakeredis run-tests

**Comment by cunla** [comment]
Got you, ok, I see the need. I am not sure how to write a test for it here so I'll merge.

**Comment by mgorny** [comment]
Thank you!

**Pull request merged**
